  - name: install packages
    yum: pkg={{ item }} state=latest update_cache=true
    with_items:
    - python-amqplib
    - python-amqp
    - pydot
    - redis
    - numpy
    - scipy
    - gcc-c++
    - gcc
    - make
    - automake
  - name: install python pip packages
    command: /usr/bin/pip install {{ item }}
    with_items:
    - celery
    - redis
    - neurolab
