#!/bin/bash

# To setup trader project by using Ansible in docker container under root user.

if ! grep python_trader_nodes /etc/ansible/hosts > /dev/null
then
    echo "
[python_trader_nodes]
localhost
" >> /etc/ansible/hosts
fi

service sshd restart && su - ansible -c "git clone https://github.com/ptro-development/ansible_python_trader.git /home/ansible/ansible_python_trader && ansible-playbook /home/ansible/ansible_python_trader/roles/python_trader_nodes.yml"
